name: Prepare QCW bundle

on: workflow_dispatch

jobs:

  build:
    runs-on: windows-latest

    steps:

    - name: 'üèóÔ∏è Install msys2'
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >-
          make
          git
          unzip
          base-devel
          mingw-w64-x86_64-toolchain
          python
          ninja
          mingw-w64-x86_64-glib2
          mingw-w64-x86_64-pixman
          python-setuptools
          mingw-w64-x86_64-gtk3
          mingw-w64-x86_64-SDL2
          mingw-w64-x86_64-go

    - name: 'üìù Checkout'
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
        submodules: true

    - name: 'üõ†Ô∏è Build gvproxy'
      working-directory: gvisor-tap-vsock
      shell: msys2 {0}
      run: |
        make gvproxy

    - name: 'üõ†Ô∏è Build podman'
      working-directory: podman
      shell: msys2 {0}
      run: |
        make podman-remote

    - name: 'üõ†Ô∏è Build qemu'
      working-directory: qemu
      shell: msys2 {0}
      run: |
        mkdir build
        cd build
        ../configure --enable-gtk --enable-sdl
        ninja

    - name: 'üì• Download xz'
      shell: msys2 {0}
      run: |
        curl -o xz.zip https://tukaani.org/xz/xz-5.2.6-windows.zip
        unzip -d xz xz.zip

    - name: 'üì¶ Pack bundle'
      shell: msys2 {0}
      run: |
        mkdir -p qcw
        cp -Lr xz/bin_x86-64 qcw/xz
        mkdir -p qcw/podman
        cp gvisor-tap-vsock/bin/gvproxy qcw/podman/gvproxy
        cp gvisor-tap-vsock/bin/gvproxy qcw/podman/gvproxy.exe
        cp podman/bin/windows/podman.exe qcw/podman/podman.exe
        cp -Lr qemu/build/qemu-bundle/a/_temp/msys64/qemu qcw/qemu
        ./add_mingw64_dlls.sh
        cp -Lr shells qcw/shells

    - name: 'üöÄ Upload artifact'
      uses: actions/upload-artifact@v3
      with:
        name: qcw-bundle
        path: qcw
